services:
    php:
        image: alpacode/php
        volumes:
            - ./:/opt/project
    nginx:
        image: alpacode/nginx
        volumes:
            - ./web:/opt/project/web

    database:
          image: postgres:${POSTGRES_VERSION:-15}
          environment:
              POSTGRES_DB: ${POSTGRES_DB:-app}
              POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
              POSTGRES_USER: ${POSTGRES_USER:-app}
          volumes:
              - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data:
